
-- Total Number of orders completed on 18th March 2023

SELECT COUNT(DISTINCT order_id) AS num_of_orders
FROM SALES
WHERE Date ='03-18-2023';

-- Total number of orders completed on 18th March 2023 by a customer with the first name 'John' and last name 'Doe'

SELECT COUNT(s.order_id) AS num_of_orders
FROM SALES AS s
JOIN CUSTOMERS c ON s.customer_id = c.customer_id
WHERE s.Date = '03-18-2023'
	AND c.first_name = 'John'
	AND c.last_name = 'Doe';

-- Total number of customers that purchased in January 2023 and the average amount spent per customer

SELECT COUNT(DISTINCT customer_id) AS total_customers, 
	AVG(Revenue) AS average_rev
FROM SALES
WHERE Date BETWEEN '01-01-2023'
	AND '01-31-2023';

-- Pull the department that generated less than $600 in 2022

SELECT i.department AS depart,
	SUM(s.Revenue) AS revenue
FROM ITEMS AS i
JOIN SALES s ON i.item_id = s.item_id
WHERE s.Date BETWEEN '2022-01-01' AND '2022-12-31'
GROUP BY i.department
HAVING SUM(s.Revenue) < 600;

-- What is the most and least revenue we have generated by an order

SELECT MAX(Revenue) AS max_order, 
	MIN(Revenue) AS min_order
FROM SALES;

-- What were the orders that were purchased in our most lucrative order

SELECT * 
FROM SALES
WHERE Revenue = (SELECT MAX(Revenue) FROM SALES);


